[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Artyom <worldbeater-dev@yandex.ru>"]

[tool.poetry.dependencies]
python = "^3.10"
Flask = "^2.0.2"
Jinja2 = "^3.0.3"
autopep8 = "^1.6.0"
SQLAlchemy = "^1.4.29"
Flask-JWT-Extended = "^4.3.1"
Flask-WTF = "^1.0.0"
email-validator = "^1.1.3"
alembic = "^1.7.5"
psycopg2-binary = "^2.9.3"
Flask-Bcrypt = "^0.7.1"
pycodestyle = "^2.8.0"
radon = "^5.1.0"
waitress = "^2.0.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-flask = "^1.2.0"
pytest-alembic = "^0.7.0"
beautifulsoup4 = "^4.10.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
